version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  greek-gods-api:
    build: .
    container_name: greek-gods-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017
    volumes:
      - .:/usr/src
      - ./dist:/usr/src/app/dist

volumes:
  mongo-data:
  node_modules:
